# Generated by Django 5.2 on 2025-06-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="auther",
            new_name="author",
        ),
    ]
